[package]

name = "portable_env"
version = "0.2.0"
edition = "2018"
authors = [ "Dariusz Antoniuk <qaston@gmail.com>" ]

[[bin]]

name = "portable_env"

[dependencies]
docopt = "*"
toml="0.5.8"
serde = "1.0.97"
serde_derive = "1.0"